spring:
  # 配置数据库连接信息
  datasource:
    # 动态数据源配置，多数据源
    dynamic:
      primary: master # 默认数据源 / 数据源组
      strict: false # 严格匹配数据源，默认false；true未匹配到指定数据源时抛异常，false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/test1?serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

# 配置 mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id # 全局主键类型
      logic-delete-field: del # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值, 默认 1
      logic-not-delete-value: 0 # 逻辑未删除值, 默认 0
  configuration:
    # 配置控制台日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置扫描的 mapper.xml 文件
  mapper-locations: classpath:mapper/*.xml
  # 配置扫描的实体类
  type-aliases-package: com.slz.springboot.entity
  # 配置扫描枚举类
  type-enums-package: com.slz.springboot.enums